
import './globals.css'
import { Container } from '@/components/Container'
import { Footer } from '@/components/Footer'
import { Chakra_Petch } from 'next/font/google'

const chakra_Petch = Chakra_Petch({
  subsets: ['latin'],
  weight: ['300', '500', '700'],
  display: 'swap'
})

export const metadata = {
  title: 'PortSync',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={chakra_Petch.className}>
        <Container>
          {children}
        </Container>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
