import './globals.css'
import { Jua } from 'next/font/google'

const jua = Jua({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'PortSync',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={jua.className}>{children}</body>
    </html>
  )
}
